### ISSUE TITLE
Do not ignore gradle.properties

### ISSUE THREAD

**Issue by murgupluoglu** [PhilippeBoisney/GithubApp#1]
Project using androidX and must have 

`android.useAndroidX=true`
`android.enableJetifier=true`

when you ignore gradle.properties its fail try to run project.

**Comment by PhilippeBoisney** [comment]
`gradle.properties` contains some private API key (Github). It's a common practice to ignore this file when it contains sensitive information.

**Comment by murgupluoglu** [comment]
I got it but i think you must create another `.properties` file for your private keys. Its hard to figure out run project without `gradle.properties`

**Comment by PhilippeBoisney** [comment]
Fixed ;)

**Comment by nichbar** [comment]
I think place a link like [Connect your app to GitHub](https://auth0.com/docs/connections/social/github) about how to get a private keys may save some time.

**Comment by murgupluoglu** [comment]
Thank you
